---
- hosts: all

  vars_files:
    - default.config.yml
  vars:
    - ansible_python_interpreter: /Users/liangyaran/.pyenv/shims/python3.7

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: homebrew

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    # - import_tasks: tasks/terminal.yml
    #   when: configure_terminal
    #   tags: ['terminal']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    # - block:
    #    - name: Run configured post-provision ansible task files.
    #       include_tasks: "{{ outer_item }}"
    #       loop_control:
    #         loop_var: outer_item
    #       with_fileglob: "{{ post_provision_tasks|default(omit) }}"
    #   tags: ['post']
